name: Focal-Foxy

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 5 * * *'

env:
  REGISTRY: ghcr.io
  ROS_DISTRO: foxy

jobs:
  ci:
    name: Focal-Foxy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build repository
        uses: ros-industrial/industrial_ci@master
        env:
          OS_NAME: ubuntu
          OS_CODE_NAME: focal
          ROS_REPO: main
          PREFIX: ${{ github.repository }}_
          DOCKER_IMAGE: ${{ env.REGISTRY }}/${{ github.repository }}:ci
          GIT_SUBMODULE_STRATEGY: normal
          TMPDIR: ${CI_PROJECT_DIR}.tmp
          BUILDER: colcon
          UNDERLAY: /root/tesseract-robotics/tesseract_planning_target_ws/install
          UPSTREAM_WORKSPACE: dependencies.rosinstall
          BEFORE_BUILD_UPSTREAM_WORKSPACE_EMBED: 'ici_with_unset_variables source /opt/ros/${{ env.ROS_DISTRO }}/setup.bash'
          ROSDEP_SKIP_KEYS: "tesseract_rviz tesseract_plugins rviz octomap_ros"
          AFTER_SCRIPT: ''
